### ISSUE TITLE
Importing .dat files to web application fails

### ISSUE THREAD

**Issue by mca-sh** [cvdelannoy/FRETboard#6]
Hello there, and thank you for this beautiful online tool.

I'd like to use it for testing but I get stuck at the very beginning. Here are the steps I followed:
1. I've selected the model `vanilla HMM` (or any other) 
2. press `Data` and select a set of correctly structured text files (3 columns separated by tabs: [example.txt](https://github.com/cvdelannoy/FRETboard/files/5610853/example.txt) but with the `.dat` extension instead)

But nothing happens after that.

I am using Mozilla Firefox 83.0 (64Bits) on Windows 8.1

Did I miss something?

**Comment by cvdelannoy** [comment]
Hi,

Thanks for your interest in FRETboard, and for filing a bug report! It seems I broke loading of .dat files when I pushed a seemingly harmless update a few weeks ago. It should be fixed now, also on the server.

Apologies for the nuisance! Don't hesitate to let me know if there's anything else.

**Comment by mca-sh** [comment]
Great! Thank you for the fix, I can import .dat files now.
